[versions]
agp = "8.6.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
firebaseDatabase = "21.0.0"
recyclerview = "1.3.2"
firebaseFirestore = "25.1.1"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
firebaseMessaging = "24.1.0"

playServicesVision = "20.1.3"
firebaseBom = "33.5.1"
cameraCore = "1.4.0"
firebaseStorage = "21.0.1"
textRecognitionKoreanVersion = "16.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

play-services-vision = { module = "com.google.android.gms:play-services-vision", version.ref = "playServicesVision" }
mlkit-text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "textRecognitionKoreanVersion" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

